FROM python:3.10-slim-bookworm
WORKDIR /app
# COPY ./test /app/test
RUN mkdir -p /app/study
COPY ./static /app/static
COPY ./code.deb /usr/src/code.deb

RUN apt-get update
RUN apt-get install wget gpg --yes
RUN echo "code code/add-microsoft-repo boolean true" | debconf-set-selections
RUN apt-get install /usr/src/code.deb --yes

RUN apt-get install graphviz --yes

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./pymcdebug /app/pymcdebug
RUN pip install /app/pymcdebug

COPY ./ppl-debugger.vsix /usr/src/ppl_debugger.vsix
RUN code --no-sandbox --user-data-dir /app --install-extension /usr/src/ppl_debugger.vsix
RUN code --no-sandbox --user-data-dir /app --install-extension ms-python.python
RUN code --no-sandbox --user-data-dir /app --install-extension ms-toolsai.jupyter

COPY ./entrypoint.sh /usr/src/entrypoint.sh
RUN chmod o+x /usr/src/entrypoint.sh

CMD ["/usr/src/entrypoint.sh"]